server:
  port: 3344

spring:
  application:
    name: cloud-config-center  #注册进Eureka服务器的微服务名
  cloud:
    config:
      server:
        git:
          uri: https://github.com/huiyalin525/springcloud-config.git #GitHub上面git仓库名字
          skip-ssl-validation: true
          ###搜索目录
          search-paths: springcloud-config
          username:
          password:
      ####读取分支
      label: master
  #rabbitMQ相关配置15672是web管理界面端口。5672是MQ访问端口
  rabbitmq:
    host: 192.168.133.128
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
#rabbitMQ相关配置，暴露bus刷新配置的端点
management:
  endpoints:  #暴露bus刷新配置的端点
    web:
      exposure:
        include: 'bus-refresh'