spring:
  application:
    name: consumer-user #最终会落实到注册中心的application上
server:
  port: 8200

eureka:
  instance:
    prefer-ip-address: true #注册服务的时候使用服务的ip地址
  client:
    service-url:
      {defaultzone: 'http://localhost:8761/eureka/'}