server:
  port: 80
spring:
  application:
    name: cloud-order-service
  zipkin:
    base-url: http://localhost:9411                         #监控的信息要在9411上面看
  sleuth:
    sampler:
      #采样率值介于0到1之间，1则表示全部采集
      probability: 1
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      #http://eureka7001.com:7001/eureka/
      defaultZone: http://localhost:7001/eureka,http://eureka7002.com:7002/eureka/
