spring:
   datasource:
     url: jdbc:mysql://localhost:3306/jpa?useUnicode=true&characterEncoding=UTF-8&serverTimezone=America/New_York&useSSL=false
     driver-class-name: com.mysql.cj.jdbc.Driver
     data-username: "root"
     data-password: "000000"
     initialization-mode: always
     type: com.mysql.cj.jdbc.MysqlConnectionPoolDataSource
   jpa:
     hibernate:
       #更新或创建数据表
       ddl-auto: update
       #控制台显示sql
     show-sql: true

   main:
     allow-bean-definition-overriding: true

